apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook
  labels:
    name: admission-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: admission-server
  template:
    metadata:
      labels:
        name: admission-server
    spec:
      containers:
      - name: admission-server
        image: hub.virtaitech.com/huyuan/admission-server:v1
        imagePullPolicy: IfNotPresent
        command:
        - admission-server
        - -logtostderr
        - -stderrthreshold=INFO
        ports:
        - containerPort: 8999
        volumeMounts:
        - name: webhook-secret
          mountPath: /etc/pki/
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: webhook-secret
        secret:
          secretName: webhook-server
---
apiVersion: v1
kind: Service
metadata:
  name: admission-service
spec:
  selector:
    name: admission-server
  ports:
  - protocol: TCP
    port: 8999
    targetPort: 8999
